// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

const lv_img_dsc_t *backgroundImage[BACKGROUND_MAX_NUM] = 
{
    &ui_img_background_png,
    &ui_img_background1_png,
    &ui_img_background2_png,
    &ui_img_background3_png,
    &ui_img_background4_png,
    &ui_img_background5_png,
};

///////////////////// VARIABLES ////////////////////
lv_obj_t * ui_Screen1;


lv_obj_t * ui_MainPage;
lv_obj_t * ui_SecondPage;
lv_obj_t * ui_ThirdPage;
lv_obj_t * ui_LabelDownloadSpeedText;
lv_obj_t * ui_LabelDownloadSpeedTextUnit;
lv_obj_t * ui_LabelUploadSpeedText;
lv_obj_t * ui_LabelUploadSpeedTextUnit;
lv_obj_t * ui_weather_icon;
lv_obj_t * ui_weather_temperature;
lv_obj_t * ui_notification;
lv_obj_t * ui_backgroundPage;

lv_obj_t * ui_Screen3;
lv_obj_t * ui_ScreenSystem;
lv_obj_t * ui____initial_actions0;

lv_obj_t * ui_tomatoClock;

static lv_timer_t *s_mainTimer ;    // 跳转主界面定时器

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////


///////////////////// FUNCTIONS ////////////////////
static void s_mainTimer_cb();

void ui_initMainTimer(void)
{
    // if(s_mainTimer == NULL) 
    {
        s_mainTimer = lv_timer_create(s_mainTimer_cb, 5000, NULL);
        lv_timer_set_repeat_count(s_mainTimer, -1);
        lv_timer_pause(s_mainTimer);
    }
}

void startMainTimer(void)
{
    lv_timer_reset(s_mainTimer);
    lv_timer_resume(s_mainTimer);
}

void reloadMainTimer()
{
    if(s_mainTimer != NULL) 
    {
        lv_timer_reset(s_mainTimer);
    }
}

void stopMainTimer()
{
    if (s_mainTimer != NULL) 
    {
        lv_timer_pause(s_mainTimer);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen_Loading_init();
    ui_Screen_Main_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
    ui_initMainTimer();
}

static void s_mainTimer_cb()
{
    // lv_timer_del(s_mainTimer);
    stopMainTimer();
    lv_disp_load_scr(ui_Screen_Main);
    // _ui_screen_change(&ui_Screen_Main, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen_Main_init);
}