// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../../managed_components/lvgl__lvgl/lvgl.h"
#include <string.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/event_groups.h"
#include "esp_system.h"
//#include "esp_event.h"
#include "esp_log.h"
#include "esp_sntp.h"
#include "ui_helpers.h"
#include "../components/ui_comp.h"
#include "../components/ui_comp_hook.h"
#include "ui_events.h"

void arise_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_ImageEntrance;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
void drawDiskInfoBar(uint8_t diskNum, uint8_t diskData[]);
void screen2SetMeter(uint8_t cpuValue, uint8_t memValue);
void screen2SetNetSpeed(uint64_t downloadSpeed, uint64_t uploadSpeed);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_MainPage;
extern lv_obj_t * ui_LabelHour;
extern lv_obj_t * ui_LabelColon;
extern lv_obj_t * ui_LabelMinute;
extern lv_obj_t * ui_LabelYear;
extern lv_obj_t * ui_LabelSlash1;
extern lv_obj_t * ui_LabelMonth;
extern lv_obj_t * ui_LabelSlash2;
extern lv_obj_t * ui_LabelDate;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_SecondPage;
extern lv_obj_t * ui_ThirdPage;
extern lv_obj_t * ui_LabelDownloadSpeedText;
extern lv_obj_t * ui_LabelDownloadSpeedTextUnit;
extern lv_obj_t * ui_LabelUploadSpeedText;
extern lv_obj_t * ui_LabelUploadSpeedTextUnit;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
void ui_event_Menu(lv_event_t * e);
extern lv_obj_t * ui_Menu;// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui____initial_actions0;

extern lv_obj_t * ui_Settings;

LV_IMG_DECLARE(ui_img_919562436);    // assets/128乘128_画板 1 副本 2.png
LV_IMG_DECLARE(ui_img_background_png);    // assets/background.png
LV_IMG_DECLARE(ui_img_background1_png);
LV_IMG_DECLARE(ui_img_background2_png);
LV_IMG_DECLARE(ui_img_background3_png);
LV_IMG_DECLARE(ui_img_background4_png);
LV_IMG_DECLARE(ui_img_background5_png);
LV_FONT_DECLARE(lv_font_source_han_sans_normal_30);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
