// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"
#include <string.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/event_groups.h"
#include "esp_system.h"
#include "esp_event.h"
#include "esp_log.h"
#include "esp_sntp.h"
#include "ui_helpers.h"
#include "../components/ui_comp.h"
#include "../components/ui_comp_hook.h"
#include "ui_events.h"

void arise_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_ImageEntrance;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_LabelHour;
extern lv_obj_t * ui_LabelColon;
extern lv_obj_t * ui_LabelMinute;
extern lv_obj_t * ui_LabelYear;
extern lv_obj_t * ui_LabelSlash1;
extern lv_obj_t * ui_LabelMonth;
extern lv_obj_t * ui_LabelSlash2;
extern lv_obj_t * ui_LabelDate;
extern lv_obj_t * ui_Label9;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Menu;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_919562436);    // assets/128乘128_画板 1 副本 2.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
