// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

static lv_timer_t *timer ;
static uint8_t rollerIndex = 0;   // 当前滚轮被选项
static lv_obj_t * ui_Menu;
static void ui_Screen_Menu_event_Menu(lv_event_t * e);

void ui_Screen_Menu_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    rollerIndex = 0;
    
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Menu = lv_roller_create(ui_Screen3);
    lv_roller_set_options(ui_Menu, "配置\n系统\n专注模式\n背景", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_Menu, lv_pct(100));
    lv_obj_set_height(ui_Menu, lv_pct(100));
    lv_obj_set_align(ui_Menu, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_Menu, &lv_font_simsun_16_cjk, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Menu, ui_Screen_Menu_event_Menu, LV_EVENT_ALL, NULL);

    lv_roller_set_selected(ui_Menu, 0, LV_ANIM_OFF);
}

static void ui_Screen_Menu_event_Menu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    
    if(event_code == LV_EVENT_SHORT_CLICKED) 
    {
        // reloadScreen3Timer();
        reloadMainTimer();

        if (rollerIndex < lv_roller_get_option_cnt(ui_Menu) - 1)
        {
            rollerIndex++;
        }
        else
        {
            rollerIndex = 0;

        }
        lv_roller_set_selected(ui_Menu, rollerIndex, LV_ANIM_ON);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        // resetScreen3Timer();
        // initScreen4Timer();
        reloadMainTimer();

        uint8_t index = lv_roller_get_selected(ui_Menu);
        if (index == 0)
        {
           _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen_Setting_init);
            // lv_scr_load(ui_ScreenSystem);
        }
        else if (index == 1)
        {
            _ui_screen_change(&ui_ScreenSystem, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen_System_init);
            
            // lv_scr_load(ui_Settings);
        }
        else if (index == 2)
        {
            _ui_screen_change(&ui_tomatoClock, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen_TomatoClock_init);
            // lv_scr_load(ui_tomatoClock);
        }
        else if (index == 3)
        {
            _ui_screen_change(&ui_backgroundPage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen_Background_init);
            // lv_scr_load(ui_backgroundPage);
        }
    }
}