// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

static lv_timer_t *timer ;

static void screen4Timer_cb(lv_timer_t *timer)
{
    resetScreen4Timer();
    _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
}

void initScreen4Timer()
{
    timer = lv_timer_create(screen4Timer_cb, 10000, NULL);
    lv_timer_set_repeat_count(timer, 1);
}

void reloadScreen4Timer()
{
    lv_timer_reset(timer);
}

void resetScreen4Timer()
{
    //lv_timer_del(timer);
    lv_timer_pause(timer);
}

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label1, "Wifi:");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
}
