// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

#define BAR_INTERVAL (10)

static char year[12];
static char month[12];
static char date[12];
static char hour[12];
static char minute[12];

static char downloadSpeedStr[20] = {0};
static char uploadSpeedStr[20] = {0};

static lv_obj_t * s_labelDate;
static lv_obj_t * s_labelTime;
static lv_obj_t * arcCpu;
static lv_obj_t * arcMemory;
static lv_obj_t * labelCpu;
static lv_obj_t * labelMemory;
static lv_obj_t * imgCpu;
static lv_obj_t * imgMemory;
static lv_timer_t *notificationTimer ;


const lv_img_dsc_t *weatherImage[40] = 
{
    &ui_img_weather0_png,
    &ui_img_weather1_png,
    &ui_img_weather2_png,
    &ui_img_weather3_png,
    &ui_img_weather4_png,
    &ui_img_weather5_png,
    &ui_img_weather6_png,
    &ui_img_weather7_png,
    &ui_img_weather8_png,
    &ui_img_weather9_png,
    &ui_img_weather10_png,
    &ui_img_weather11_png,
    &ui_img_weather12_png,
    &ui_img_weather13_png,
    &ui_img_weather14_png,
    &ui_img_weather15_png,
    &ui_img_weather16_png,
    &ui_img_weather17_png,
    &ui_img_weather18_png,
    &ui_img_weather19_png,
    &ui_img_weather20_png,
    &ui_img_weather21_png,
    &ui_img_weather22_png,
    &ui_img_weather23_png,
    &ui_img_weather24_png,
    &ui_img_weather25_png,
    &ui_img_weather26_png,
    &ui_img_weather27_png,
    &ui_img_weather28_png,
    &ui_img_weather29_png,
    &ui_img_weather30_png,
    &ui_img_weather31_png,
    &ui_img_weather32_png,
    &ui_img_weather33_png,
    &ui_img_weather34_png,
    &ui_img_weather35_png,
    &ui_img_weather36_png,
    &ui_img_weather37_png,
    &ui_img_weather38_png,
    &ui_img_weather99_png
};

static lv_disp_rot_t rotation = LV_DISP_ROT_NONE;
static char cpuUsageStr[12];
static char memUsageStr[12];
void screen2SetCpuValue(uint8_t v)
{
    if (v <= 100 && v >= 0)
    {
        sprintf(cpuUsageStr, "%d", v);
        // if (arcCpu != NULL)
        // {
        //     lv_arc_set_value(arcCpu, v);
        // }
        lv_obj_set_style_img_recolor_opa(imgCpu, v, LV_PART_MAIN | LV_STATE_DEFAULT);
        
        if (labelCpu != NULL)
        {
            lv_label_set_text_static(labelCpu, cpuUsageStr);
            // lv_label_set_text(labelCpu, cpuUsageStr);
        }
        
    }
}

void screen2SetMemValue(uint8_t v)
{
    if (v <= 100 && v >= 0)
    {
        sprintf(memUsageStr, "%d", v);
        // if (arcMemory!= NULL)
        // {
        //     lv_arc_set_value(arcMemory, v);
        // }
        lv_obj_set_style_img_recolor_opa(imgMemory, v, LV_PART_MAIN | LV_STATE_DEFAULT);
        if (labelMemory != NULL)
        {
            lv_label_set_text_static(labelMemory, memUsageStr);
        }
        
    }
}

/**
 * @brief 时间刷新定时器
 */
void timeUpdateTimer(lv_timer_t *timer)
{
    time_t now;
    char buffer[80];
    struct tm timeinfo;
    time(&now);
    setenv("TZ", "CST-8", 1);
    tzset();
    localtime_r(&now, &timeinfo);

    lv_label_set_text_fmt(s_labelDate, "%4d-%02d-%02d", timeinfo.tm_year+1900, timeinfo.tm_mon+1, timeinfo.tm_mday);
    lv_label_set_text_fmt(s_labelTime, "%02d:%02d", timeinfo.tm_hour, timeinfo.tm_min);

}

void ui_Screen2NotificationTimer()
{
    lv_label_set_text(ui_notification, "");
    // 实现刷新效果
    lv_obj_invalidate(ui_MainPage);
}

void diskSetInfo()
{

}

static lv_obj_t *bar[20] = {0};
static lv_obj_t *label[20] = {0};

void drawDiskInfoBar(uint8_t diskNum, uint8_t diskData[])
{
    static lv_style_t style_indic;
    static uint8_t firstRecFlag = 0;

    lv_style_init(&style_indic);
    lv_style_set_bg_opa(&style_indic, LV_OPA_COVER);
    lv_style_set_bg_color(&style_indic, lv_palette_main(LV_PALETTE_BLUE));
    lv_style_set_bg_grad_color(&style_indic, lv_palette_main(LV_PALETTE_BLUE));
    lv_style_set_bg_grad_dir(&style_indic, LV_GRAD_DIR_VER);

    for (int i = 0; i < diskNum; i++) 
    {
        char text[2] = {0,'\0'};
        if (firstRecFlag == 0)
        {
            bar[i] = lv_bar_create(ui_ThirdPage);
            label[i] = lv_label_create(ui_ThirdPage);
            lv_obj_add_style(bar[i], &style_indic, LV_PART_INDICATOR);
            lv_obj_set_size(bar[i], (240-(BAR_INTERVAL*diskNum+1))/diskNum, 100);
            //lv_obj_center(bar[i]);
            lv_obj_set_x(bar[i], BAR_INTERVAL + ((240-(BAR_INTERVAL*diskNum+1))/diskNum)*i + BAR_INTERVAL*i);
            lv_obj_set_y(bar[i], 10);   
            lv_bar_set_range(bar[i], 0, 100);

            lv_obj_set_x(label[i], BAR_INTERVAL + ((240-(BAR_INTERVAL*diskNum+1))/diskNum)*i + BAR_INTERVAL*i + 10);
            lv_obj_set_y(label[i], 110);
        }
        
        lv_bar_set_value(bar[i], diskData[i * 2 + 1],LV_ANIM_OFF);

        text[0] = diskData[i * 2];
        lv_label_set_text(label[i],text);
        lv_obj_set_style_text_font(label[i], &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    }
    firstRecFlag = 1;
}


void screen2SetMeter(uint8_t cpuValue, uint8_t memValue)
{
    screen2SetCpuValue(cpuValue);
    screen2SetMemValue(memValue);
}

void screen2SetNetSpeed(uint64_t downloadSpeed, uint64_t uploadSpeed)
{
    
    if (downloadSpeed > 1024)
    {
        sprintf(downloadSpeedStr, "%d", (int)(downloadSpeed /1024));
        lv_label_set_text_static(ui_LabelDownloadSpeedText, downloadSpeedStr);
        lv_label_set_text_static(ui_LabelDownloadSpeedTextUnit, "MB/s");
    }
    else
    {
        sprintf(downloadSpeedStr, "%d", (int)(downloadSpeed));
        lv_label_set_text_static(ui_LabelDownloadSpeedText, downloadSpeedStr);
        lv_label_set_text_static(ui_LabelDownloadSpeedTextUnit, "KB/s");
    }

    if (uploadSpeed > 1024)
    {
        sprintf(uploadSpeedStr, "%d", (int)(uploadSpeed/1024));
        lv_label_set_text_static(ui_LabelUploadSpeedText, uploadSpeedStr);
        lv_label_set_text_static(ui_LabelUploadSpeedTextUnit, "MB/s");
    }
    else
    {
        sprintf(uploadSpeedStr, "%d", (int)(uploadSpeed));
        lv_label_set_text_static(ui_LabelUploadSpeedText, uploadSpeedStr);
        lv_label_set_text_static(ui_LabelUploadSpeedTextUnit, "KB/s");
    }
}

void createMeter1(lv_obj_t *scr)
{

    imgCpu = lv_img_create(scr);
    lv_img_set_src(imgCpu, &ui_img_cpu_png);
    lv_obj_set_width(imgCpu, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(imgCpu, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(imgCpu, -55);
    lv_obj_set_y(imgCpu, -10);
    lv_obj_set_align(imgCpu, LV_ALIGN_CENTER);
    lv_obj_add_flag(imgCpu, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(imgCpu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(imgCpu, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(imgCpu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    labelCpu = lv_label_create(scr);
    lv_obj_set_style_text_font(labelCpu, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(labelCpu, lv_color_hex3(0xfff), 0);
    lv_label_set_text(labelCpu, "CPU");
    lv_obj_center(labelCpu);
    lv_obj_set_pos(labelCpu, -55, -10);
}

void createMeter2(lv_obj_t *scr)
{
    imgMemory = lv_img_create(scr);
    lv_img_set_src(imgMemory, &ui_img_memory_png);
    lv_obj_set_width(imgMemory, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(imgMemory, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(imgMemory, 55);
    lv_obj_set_y(imgMemory, 5);
    lv_obj_set_align(imgMemory, LV_ALIGN_CENTER);
    lv_obj_add_flag(imgMemory, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(imgMemory, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(imgMemory, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(imgMemory, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    labelMemory = lv_label_create(scr);
    lv_obj_set_style_text_font(labelMemory, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(labelMemory, lv_color_hex3(0xfff), 0);
    lv_label_set_text(labelMemory, "MEM");
    lv_obj_center(labelMemory);
    lv_obj_set_pos(labelMemory, 54, -6);

}

void createSpeedArrow(lv_obj_t *scr)
{
    static lv_style_t styleLineUpload, styleLineDownload;
    static lv_point_t line_points[] = { {115, 110}, {115, 130}, {106, 125}, {125, 130}, {125, 110}, {134, 115} };
    lv_style_set_line_rounded(&styleLineUpload, true);
    lv_style_set_line_width(&styleLineUpload, 3);
    lv_style_set_line_color(&styleLineUpload, lv_palette_main(LV_PALETTE_ORANGE));

    lv_style_set_line_rounded(&styleLineDownload, true);
    lv_style_set_line_width(&styleLineDownload, 3);
    lv_style_set_line_color(&styleLineDownload, lv_palette_main(LV_PALETTE_BLUE));

    lv_obj_t *lineUpload, *lineDownload;
    lineUpload = lv_line_create(scr);
    lv_line_set_points(lineUpload,line_points,3);
    
    lv_obj_add_style(lineUpload, &styleLineUpload, 0);

    lineDownload = lv_line_create(scr);
    lv_line_set_points(lineDownload,line_points+3,3);
    
    lv_obj_add_style(lineDownload, &styleLineDownload, 0);

}

void createSpeedText(lv_obj_t *scr)
{
    ui_LabelDownloadSpeedText = lv_label_create(scr);
    ui_LabelDownloadSpeedTextUnit = lv_label_create(scr);
    ui_LabelUploadSpeedText = lv_label_create(scr);
    ui_LabelUploadSpeedTextUnit = lv_label_create(scr);

    lv_obj_set_width(ui_LabelDownloadSpeedText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDownloadSpeedText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDownloadSpeedText, 15);
    lv_obj_set_y(ui_LabelDownloadSpeedText, 110);
    lv_obj_set_style_text_color(ui_LabelDownloadSpeedText, lv_color_hex(0xFFFFFF), 0);
    // lv_obj_set_align(ui_LabelSpeedText, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LabelDownloadSpeedText, "100");
    lv_obj_set_style_text_font(ui_LabelDownloadSpeedText, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_width(ui_LabelUploadSpeedText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelUploadSpeedText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelUploadSpeedText, 140);
    lv_obj_set_y(ui_LabelUploadSpeedText, 110);
    lv_obj_set_style_text_color(ui_LabelUploadSpeedText, lv_color_hex(0xFFFFFF), 0);
    lv_label_set_text(ui_LabelUploadSpeedText, "100");
    lv_obj_set_style_text_font(ui_LabelUploadSpeedText, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    
    lv_obj_set_width(ui_LabelDownloadSpeedTextUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDownloadSpeedTextUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_update_layout(ui_LabelDownloadSpeedText);
    lv_obj_set_x(ui_LabelDownloadSpeedTextUnit, lv_obj_get_width(ui_LabelDownloadSpeedText) + 20);
    lv_obj_set_y(ui_LabelDownloadSpeedTextUnit, 110);
    lv_obj_set_style_text_color(ui_LabelDownloadSpeedTextUnit, lv_color_hex(0xFFFFFF), 0);
    lv_label_set_text(ui_LabelDownloadSpeedTextUnit, "KB/s");
    lv_obj_set_style_text_font(ui_LabelDownloadSpeedTextUnit, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_width(ui_LabelUploadSpeedTextUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelUploadSpeedTextUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_update_layout(ui_LabelUploadSpeedText);
    lv_obj_set_x(ui_LabelUploadSpeedTextUnit, lv_obj_get_width(ui_LabelUploadSpeedText) + 145);
    lv_obj_set_y(ui_LabelUploadSpeedTextUnit, 110);
    lv_obj_set_style_text_color(ui_LabelUploadSpeedTextUnit, lv_color_hex(0xFFFFFF), 0);
    lv_label_set_text(ui_LabelUploadSpeedTextUnit, "KB/s");
    lv_obj_set_style_text_font(ui_LabelUploadSpeedTextUnit, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
}

void ui_Screen2_change_display()
{
    static uint8_t displayIndex = 0;

    if(displayIndex == 0)
    {
        lv_obj_clear_flag(ui_MainPage, LV_OBJ_FLAG_HIDDEN);     /// Flags
        lv_obj_add_flag(ui_SecondPage, LV_OBJ_FLAG_HIDDEN);     /// Flags
        displayIndex = 1;
    }
    else if(displayIndex == 1)
    {
        lv_obj_clear_flag(ui_SecondPage, LV_OBJ_FLAG_HIDDEN);     /// Flags
        lv_obj_add_flag(ui_MainPage, LV_OBJ_FLAG_HIDDEN);     /// Flags
        displayIndex = 0;
    }
}

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_timer_t *timer ;

    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Screen2, &ui_img_background1_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Screen2, lv_color_hex(0xFFFFFF), 0);

    ui_MainPage = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_MainPage);
    lv_obj_set_width(ui_MainPage, 240);
    lv_obj_set_height(ui_MainPage, 135);
    lv_obj_set_align(ui_MainPage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MainPage, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_MainPage, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    s_labelTime = lv_label_create(ui_MainPage);
    lv_obj_set_width(s_labelTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(s_labelTime, LV_SIZE_CONTENT);    /// 1
    // lv_obj_set_x(s_labelTime, 10);
    // lv_obj_set_y(s_labelTime, 0);
    lv_obj_set_align(s_labelTime, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(s_labelTime, "Time");
    lv_obj_set_style_text_font(s_labelTime, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    s_labelDate = lv_label_create(ui_MainPage);
    lv_obj_set_width(s_labelDate, LV_SIZE_CONTENT);   /// 10
    lv_obj_set_height(s_labelDate, LV_SIZE_CONTENT);    /// 10
    // lv_obj_set_x(s_labelDate, 50);
    // lv_obj_set_y(s_labelDate, 0);
    lv_obj_set_align(s_labelDate, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(s_labelDate, "Date");
    lv_obj_set_style_text_font(s_labelDate, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_SecondPage = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_SecondPage);
    lv_obj_set_width(ui_SecondPage, 240);
    lv_obj_set_height(ui_SecondPage, 135);
    lv_obj_set_align(ui_SecondPage, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SecondPage, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    // lv_obj_add_flag(ui_SecondPage, LV_OBJ_FLAG_HIDDEN);     /// Flags

    createMeter1(ui_SecondPage);
    createMeter2(ui_SecondPage);
    createSpeedArrow(ui_SecondPage);
    createSpeedText(ui_SecondPage);

    ui_ThirdPage = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_ThirdPage);
    lv_obj_set_width(ui_ThirdPage, 240);
    lv_obj_set_height(ui_ThirdPage, 135);
    lv_obj_set_align(ui_ThirdPage, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ThirdPage, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    // 创建天气图标
    ui_weather_icon = lv_img_create(ui_MainPage);
    lv_img_set_src(ui_weather_icon, weatherImage[39]);
    lv_obj_set_pos(ui_weather_icon, 0, 0);
    // 创建温度标签
    ui_weather_temperature = lv_label_create(ui_MainPage);
    lv_label_set_text(ui_weather_temperature, "NULL");
    lv_obj_set_pos(ui_weather_temperature, 0, 60);
    lv_obj_set_style_text_font(ui_weather_temperature, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    // 通知标签
    ui_notification = lv_label_create(ui_MainPage);
    lv_label_set_text(ui_notification, "欢迎进入Sparrow的世界!");
    lv_obj_align(ui_notification, LV_ALIGN_TOP_RIGHT, 0, 0);
    lv_obj_set_width(ui_notification, 150);
    lv_obj_set_style_text_font(ui_notification, &lv_font_source_han_sans_normal_30, LV_STATE_DEFAULT);
    lv_label_set_long_mode(ui_notification, LV_LABEL_LONG_SCROLL);


    lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);

    timer = lv_timer_create(timeUpdateTimer, 1000, NULL);
    lv_timer_set_repeat_count(timer, -1);

    notificationTimer = lv_timer_create(ui_Screen2NotificationTimer, 10000, NULL);
    lv_timer_set_repeat_count(notificationTimer, 1);
}

void ui_screen2SetWeatherIcon(uint8_t index)
{
    // lv_mem_free(ui_weather_icon);
    // printf("img weatherCode = %d\r\n", index);
    // ui_weather_icon = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_weather_icon, weatherImage[index]);
}

void ui_screen2SetWeatherTemperature(char *temperature)
{
    char cmbTemperature[10];
    strcpy(cmbTemperature, temperature);
    strcat(cmbTemperature,"°C");
    lv_label_set_text(ui_weather_temperature, cmbTemperature);
}

void ui_screen2SetNotification(char *notification)
{
    lv_label_set_text(ui_notification, notification);
    // 实现刷新效果
    lv_obj_invalidate(ui_MainPage);
    lv_timer_set_repeat_count(notificationTimer, 1);
}