// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

static lv_obj_t * ui_ImageEntrance;

static void loadingJumpTimer(lv_timer_t *timer)
{
    lv_disp_load_scr(ui_Screen_Main);
    lv_timer_del(timer);
}

void ui_Screen_Loading_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_timer_t *timer ;

    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageEntrance = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_ImageEntrance, &icon_sparrow);
    lv_obj_set_width(ui_ImageEntrance, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageEntrance, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageEntrance, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageEntrance, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageEntrance, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_scr_load_anim(ui_Screen1, LV_SCR_LOAD_ANIM_OVER_RIGHT, 1000, 1000, true);

     timer = lv_timer_create(loadingJumpTimer, 3000, NULL);
     lv_timer_set_repeat_count(timer, 1);
}
