// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Menu = lv_roller_create(ui_Screen3);
    lv_roller_set_options(ui_Menu, "Setting\nOption 2\nOption 3", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_Menu, lv_pct(100));
    lv_obj_set_height(ui_Menu, lv_pct(100));
    lv_obj_set_align(ui_Menu, LV_ALIGN_CENTER);


}
