// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

static lv_timer_t *timer ;

static void screen3Timer_cb(lv_timer_t *timer)
{
    _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
}

void initScreen3Timer()
{
    if(timer == NULL) {
        timer = lv_timer_create(screen3Timer_cb, 5000, NULL);
        lv_timer_set_repeat_count(timer, 1);
    }
}

void reloadScreen3Timer()
{
    if(timer != NULL) {
        lv_timer_reset(timer);
    }
    else
    {
        timer = lv_timer_create(screen3Timer_cb, 5000, NULL);
        lv_timer_set_repeat_count(timer, 1);
    }
}

void resetScreen3Timer()
{
    if (timer != NULL) 
    {
        lv_timer_del(timer);
        //lv_timer_pause(timer);
    }
    timer = NULL;
}

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Menu = lv_roller_create(ui_Screen3);
    lv_roller_set_options(ui_Menu, "Settings\nSystem\nTheme", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_Menu, lv_pct(100));
    lv_obj_set_height(ui_Menu, lv_pct(100));
    lv_obj_set_align(ui_Menu, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_Menu, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Menu, ui_event_Menu, LV_EVENT_ALL, NULL);

    lv_roller_set_selected(ui_Menu, 0, LV_ANIM_OFF);
}